// ui-widgets.js — AUTO-GENERATED by Claude Code from Stream product repo
// Include with: <script src="/ui-widgets.js"></script>
// Requires: brand-extract.css to be loaded first

(function () {
  "use strict";

  // --- Shared helpers ---

  function el(selector) {
    return typeof selector === "string"
      ? document.querySelector(selector)
      : selector;
  }

  function css(prop, fallback) {
    return "var(" + prop + ", " + fallback + ")";
  }

  // Shared base styles injected once
  var baseInjected = false;
  function injectBase() {
    if (baseInjected) return;
    baseInjected = true;
    var s = document.createElement("style");
    s.textContent = [
      ".sw-widget { font-family: var(--brand-font-family, Inter, -apple-system, BlinkMacSystemFont, sans-serif); color: var(--brand-ink, #333); box-sizing: border-box; }",
      ".sw-widget *, .sw-widget *::before, .sw-widget *::after { box-sizing: border-box; margin: 0; padding: 0; }",
      ".sw-badge { display: inline-block; padding: 2px 8px; border-radius: var(--brand-radius-full, 9999px); font-size: var(--brand-p4-size, 12px); line-height: var(--brand-p4-line, 16px); font-weight: var(--brand-font-weight-medium, 450); }",
    ].join("\n");
    document.head.appendChild(s);
  }

  // --- 1. ProblemListWidget ---

  function ProblemListWidget(selector, options) {
    injectBase();
    var root = el(selector);
    if (!root) return;
    options = options || {};
    var onSelect = options.onSelect || function () {};
    var problems = options.problems || [
      { name: "Type 2 Diabetes Mellitus", status: "Active", encounters: 12, icd: "E11.9" },
      { name: "Essential Hypertension", status: "Active", encounters: 10, icd: "I10" },
      { name: "Hyperlipidemia", status: "Stable", encounters: 8, icd: "E78.5" },
      { name: "Chronic Low Back Pain", status: "Active", encounters: 5, icd: "M54.5" },
      { name: "Seasonal Allergic Rhinitis", status: "Resolved", encounters: 2, icd: "J30.2" },
    ];

    var statusColors = {
      Active:   { bg: "var(--brand-primary-10, #E6F1FF)",   text: "var(--brand-primary-60, #275B9C)" },
      Stable:   { bg: "var(--brand-success-10, #EEFDF0)",   text: "var(--brand-success-50, #037D54)" },
      Resolved: { bg: "var(--brand-neutral-20, #E7EBEE)",    text: "var(--brand-neutral-60, #5F7180)" },
    };

    var selectedIdx = 0;

    function render() {
      var html = '<div class="sw-widget" style="width:100%;background:var(--brand-surface,#fff);border-radius:var(--brand-radius-lg,12px);box-shadow:var(--brand-shadow-note, 0 2px 8px 4px rgba(0,0,0,.115));overflow:hidden;">';
      html += '<div style="padding:16px 16px 12px;border-bottom:1px solid var(--brand-neutral-20,#E7EBEE);"><span style="font-size:var(--brand-h6-size,14px);font-weight:var(--brand-font-weight-semibold,500);color:var(--brand-ink,#333);">Problem List</span><span style="float:right;font-size:var(--brand-p4-size,12px);color:var(--brand-ink-medium,#666);">' + problems.length + ' problems</span></div>';
      for (var i = 0; i < problems.length; i++) {
        var p = problems[i];
        var sc = statusColors[p.status] || statusColors.Active;
        var isSelected = i === selectedIdx;
        var bg = isSelected ? "var(--brand-functional-10, #DCF3F5)" : "transparent";
        var leftBorder = isSelected ? "3px solid var(--brand-functional-60, #27959C)" : "3px solid transparent";
        var opacity = p.status === "Resolved" ? "0.7" : "1";
        html += '<div data-idx="' + i + '" style="padding:10px 16px;border-left:' + leftBorder + ';background:' + bg + ';cursor:pointer;display:flex;align-items:center;justify-content:space-between;transition:background .2s;opacity:' + opacity + ';">';
        html += '<div style="flex:1;min-width:0;">';
        html += '<div style="font-size:var(--brand-p3-size,14px);font-weight:var(--brand-font-weight-medium,450);white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">' + p.name + '</div>';
        html += '<div style="font-size:var(--brand-p5-size,10px);color:var(--brand-ink-medium,#666);margin-top:2px;">' + p.icd + ' &middot; ' + p.encounters + ' encounters</div>';
        html += '</div>';
        html += '<span class="sw-badge" style="background:' + sc.bg + ';color:' + sc.text + ';margin-left:8px;flex-shrink:0;">' + p.status + '</span>';
        html += '</div>';
      }
      html += '</div>';
      root.innerHTML = html;

      var rows = root.querySelectorAll("[data-idx]");
      for (var j = 0; j < rows.length; j++) {
        rows[j].addEventListener("click", function () {
          selectedIdx = parseInt(this.getAttribute("data-idx"), 10);
          render();
          onSelect(problems[selectedIdx], selectedIdx);
        });
      }
    }

    render();
  }

  // --- 2. EncounterNoteWidget ---

  function EncounterNoteWidget(selector, options) {
    injectBase();
    var root = el(selector);
    if (!root) return;
    options = options || {};
    var data = options.data || {
      title: "Type 2 Diabetes Mellitus",
      icd: ["E11.65", "E11.9"],
      updated: "Mar 28, 2026",
      status: "Active",
      subjective: "DM2 f/u. BG 140-180 fasting. Compliant w/ metformin 500 BID. Reports increased fatigue x2 wks. No polyuria, polydipsia, or vision changes. Diet adherence fair — skipping meals on busy days.",
      objective: "Vitals: BP 128/82, HR 74, Wt 198 lbs (prev 201)\nLabs: HbA1c 7.8% (prev 8.2%), fasting glucose 162, Cr 0.9",
      assessment: "Improving but uncontrolled DM2. HbA1c trending down. Fatigue may be related to glycemic variability.",
      plan: ["Increase metformin to 1000mg BID", "Recheck HbA1c in 3 months", "Nutrition referral for meal planning", "F/u 3 months"],
    };

    var statusColors = {
      Active:   { bg: "var(--brand-primary-10, #E6F1FF)",   text: "var(--brand-primary-60, #275B9C)" },
      Stable:   { bg: "var(--brand-success-10, #EEFDF0)",   text: "var(--brand-success-50, #037D54)" },
      Resolved: { bg: "var(--brand-neutral-20, #E7EBEE)",    text: "var(--brand-neutral-60, #5F7180)" },
    };
    var sc = statusColors[data.status] || statusColors.Active;

    var icdHtml = data.icd
      .map(function (c) {
        return '<span style="display:inline-block;padding:2px 8px;border-radius:var(--brand-radius-md,6px);background:var(--brand-functional-10,#DCF3F5);font-size:var(--brand-p4-size,12px);color:var(--brand-functional-80,#12787E);margin-right:4px;">' + c + "</span>";
      })
      .join("");

    var planHtml = data.plan
      .map(function (item) {
        return '<div style="display:flex;align-items:baseline;gap:6px;margin-bottom:2px;"><span style="color:var(--brand-ink-medium,#666);">-</span><span>' + item + "</span></div>";
      })
      .join("");

    var sections = [
      { label: "Subjective", content: "<p>" + data.subjective + "</p>" },
      { label: "Objective", content: "<p style='white-space:pre-line;'>" + data.objective + "</p>" },
      { label: "Assessment", content: "<p>" + data.assessment + "</p>" },
      { label: "Plan", content: planHtml },
    ];

    var sectionsHtml = sections
      .map(function (s) {
        return '<div style="margin-bottom:10px;"><div style="font-size:var(--brand-p4-size,12px);color:var(--brand-ink-medium,#666);font-weight:var(--brand-font-weight-medium,450);margin-bottom:2px;">' + s.label + '</div><div style="font-size:var(--brand-p3-size,14px);line-height:var(--brand-p3-line,20px);">' + s.content + "</div></div>";
      })
      .join("");

    root.innerHTML =
      '<div class="sw-widget" style="width:100%;background:var(--brand-surface,#fff);border-radius:var(--brand-radius-md,6px);box-shadow:var(--brand-shadow-note, 0 2px 8px 4px rgba(0,0,0,.115));overflow:hidden;">' +
      '<div style="padding:12px 16px;border-bottom:1px solid var(--brand-neutral-20,#E7EBEE);display:flex;align-items:center;justify-content:space-between;">' +
      '<div><div style="font-size:var(--brand-h6-size,14px);font-weight:var(--brand-font-weight-semibold,500);">' + data.title + '</div><div style="font-size:var(--brand-p5-size,10px);color:var(--brand-ink-medium,#666);margin-top:2px;">Last updated ' + data.updated + "</div></div>" +
      '<span class="sw-badge" style="background:' + sc.bg + ";color:" + sc.text + ';">' + data.status + "</span>" +
      "</div>" +
      '<div style="padding:8px 16px 4px;">' + icdHtml + "</div>" +
      '<div style="padding:8px 16px 16px;">' + sectionsHtml + "</div>" +
      "</div>";
  }

  // --- 3. TaskListWidget ---

  function TaskListWidget(selector, options) {
    injectBase();
    var root = el(selector);
    if (!root) return;
    options = options || {};
    var tasks = options.tasks || [
      { text: "Recheck HbA1c in 3 months", due: "Jun 28", tag: "Routine", done: false },
      { text: "Refer to nutrition for meal planning", due: "Apr 10", tag: "Routine", done: false },
      { text: "Review abnormal LFTs — hepatology consult?", due: "Apr 5", tag: "Urgent", done: false },
      { text: "Refill lisinopril 20mg — 90-day supply", due: "Apr 12", tag: "Routine", done: true },
    ];

    var tagColors = {
      Routine: { bg: "var(--brand-functional-10, #DCF3F5)", text: "var(--brand-functional-80, #12787E)" },
      Urgent:  { bg: "var(--brand-error-10, #FDF5F5)",      text: "var(--brand-error-50, #DC362E)" },
    };

    function render() {
      var html = '<div class="sw-widget" style="width:100%;background:var(--brand-surface,#fff);border-radius:var(--brand-radius-lg,12px);box-shadow:var(--brand-shadow-note, 0 2px 8px 4px rgba(0,0,0,.115));overflow:hidden;">';
      html += '<div style="padding:16px 16px 12px;border-bottom:1px solid var(--brand-neutral-20,#E7EBEE);font-size:var(--brand-h6-size,14px);font-weight:var(--brand-font-weight-semibold,500);">Tasks</div>';
      for (var i = 0; i < tasks.length; i++) {
        var t = tasks[i];
        var tc = tagColors[t.tag] || tagColors.Routine;
        var textStyle = t.done ? "text-decoration:line-through;color:var(--brand-ink-disabled,#C6C6C6);" : "";
        var checkColor = t.done ? "var(--brand-success-50, #037D54)" : "var(--brand-neutral-40, #C3CCD5)";
        var checkBg = t.done ? "var(--brand-success-10, #EEFDF0)" : "transparent";
        var checkMark = t.done ? "&#10003;" : "";
        html += '<div data-task="' + i + '" style="padding:10px 16px;display:flex;align-items:center;gap:10px;border-bottom:1px solid var(--brand-neutral-10,#F3F5F7);cursor:pointer;transition:background .15s;" onmouseenter="this.style.background=\'var(--brand-neutral-10,#F3F5F7)\'" onmouseleave="this.style.background=\'transparent\'">';
        html += '<div style="width:18px;height:18px;border-radius:var(--brand-radius-sm,4px);border:2px solid ' + checkColor + ';background:' + checkBg + ';display:flex;align-items:center;justify-content:center;font-size:12px;color:' + checkColor + ';flex-shrink:0;transition:all .2s;">' + checkMark + '</div>';
        html += '<div style="flex:1;min-width:0;font-size:var(--brand-p3-size,14px);' + textStyle + 'white-space:nowrap;overflow:hidden;text-overflow:ellipsis;">' + t.text + '</div>';
        html += '<span style="font-size:var(--brand-p5-size,10px);color:var(--brand-ink-medium,#666);flex-shrink:0;margin-right:6px;">' + t.due + '</span>';
        html += '<span class="sw-badge" style="background:' + tc.bg + ';color:' + tc.text + ';flex-shrink:0;">' + t.tag + '</span>';
        html += '</div>';
      }
      html += '</div>';
      root.innerHTML = html;

      var rows = root.querySelectorAll("[data-task]");
      for (var j = 0; j < rows.length; j++) {
        rows[j].addEventListener("click", function () {
          var idx = parseInt(this.getAttribute("data-task"), 10);
          tasks[idx].done = !tasks[idx].done;
          render();
        });
      }
    }

    render();
  }

  // --- 4. WaveformWidget ---

  function WaveformWidget(selector, options) {
    injectBase();
    var root = el(selector);
    if (!root) return;
    options = options || {};
    var barCount = options.bars || 24;
    var running = !!options.autoStart;
    var frameId = null;

    var styleId = "sw-waveform-style";
    if (!document.getElementById(styleId)) {
      var s = document.createElement("style");
      s.id = styleId;
      s.textContent = [
        "@keyframes sw-wave { 0%,100% { transform: scaleY(0.15); } 50% { transform: scaleY(1); } }",
      ].join("\n");
      document.head.appendChild(s);
    }

    function render() {
      var bars = "";
      for (var i = 0; i < barCount; i++) {
        var delay = (i * 0.12).toFixed(2);
        var anim = running ? "sw-wave 1.2s ease-in-out " + delay + "s infinite" : "none";
        var height = running ? "100%" : "15%";
        bars += '<div style="flex:1;max-width:6px;height:' + height + ';background:var(--brand-functional-60,#27959C);border-radius:3px;transform-origin:center;animation:' + anim + ';transition:height .3s;"></div>';
      }

      var btnLabel = running ? "Stop" : "Start";
      var btnBg = running ? "var(--brand-secondary, #ad311b)" : "var(--brand-success-50, #037D54)";

      root.innerHTML =
        '<div class="sw-widget" style="width:100%;">' +
        '<div style="display:flex;align-items:center;gap:12px;">' +
        '<div style="flex:1;height:48px;display:flex;align-items:center;gap:2px;padding:8px 12px;background:var(--brand-neutral-05,#FAFAFA);border-radius:var(--brand-radius-md,6px);box-shadow:inset 4px 0 6px -4px rgba(0,0,0,.2), inset -4px 0 6px -4px rgba(0,0,0,.2);overflow:hidden;">' +
        bars +
        "</div>" +
        '<button id="sw-wave-toggle" style="padding:6px 16px;border:none;border-radius:var(--brand-radius-md,6px);background:' + btnBg + ';color:#fff;font-size:var(--brand-p3-size,14px);font-family:inherit;font-weight:var(--brand-font-weight-medium,450);cursor:pointer;transition:background .2s;">' + btnLabel + "</button>" +
        "</div></div>";

      document.getElementById("sw-wave-toggle").addEventListener("click", function () {
        running = !running;
        render();
      });
    }

    render();
  }

  // --- 5. ProblemSummaryCard ---

  function ProblemSummaryCard(selector, options) {
    injectBase();
    var root = el(selector);
    if (!root) return;
    options = options || {};
    var data = options.data || {
      title: "Type 2 Diabetes Mellitus",
      status: "Active",
      icd: "E11.65",
      summary: "HbA1c trending down from 8.2% to 7.8% over past 3 months. Metformin increased to 1000mg BID last visit. Patient reports improved adherence but continued fasting hyperglycemia. Nutrition referral pending.",
      lastUpdated: "3 days ago",
    };

    var statusColors = {
      Active:   { bg: "var(--brand-primary-10, #E6F1FF)",   text: "var(--brand-primary-60, #275B9C)" },
      Stable:   { bg: "var(--brand-success-10, #EEFDF0)",   text: "var(--brand-success-50, #037D54)" },
      Resolved: { bg: "var(--brand-neutral-20, #E7EBEE)",    text: "var(--brand-neutral-60, #5F7180)" },
    };
    var sc = statusColors[data.status] || statusColors.Active;

    root.innerHTML =
      '<div class="sw-widget" style="width:100%;background:var(--brand-surface,#fff);border-radius:var(--brand-radius-md,6px);box-shadow:var(--brand-shadow-note, 0 2px 8px 4px rgba(0,0,0,.115));overflow:hidden;">' +
      '<div style="padding:12px 16px;border-bottom:1px solid var(--brand-neutral-20,#E7EBEE);display:flex;align-items:center;justify-content:space-between;">' +
      '<div style="display:flex;align-items:center;gap:8px;">' +
      '<span style="font-size:var(--brand-h6-size,14px);font-weight:var(--brand-font-weight-semibold,500);">' + data.title + '</span>' +
      '<span style="font-size:var(--brand-p5-size,10px);padding:1px 6px;border-radius:var(--brand-radius-sm,4px);background:var(--brand-functional-10,#DCF3F5);color:var(--brand-functional-80,#12787E);">' + data.icd + '</span>' +
      '</div>' +
      '<span class="sw-badge" style="background:' + sc.bg + ";color:" + sc.text + ';">' + data.status + "</span>" +
      "</div>" +
      '<div style="padding:12px 16px;font-size:var(--brand-p3-size,14px);line-height:var(--brand-p3-line,20px);color:var(--brand-ink,#333);">' + data.summary + "</div>" +
      '<div style="padding:8px 16px 12px;display:flex;align-items:center;justify-content:space-between;font-size:var(--brand-p4-size,12px);color:var(--brand-ink-medium,#666);">' +
      '<span>Updated ' + data.lastUpdated + "</span>" +
      '<a href="#" onclick="return false;" style="color:var(--brand-primary-60,#275B9C);text-decoration:none;font-weight:var(--brand-font-weight-medium,450);">View history &rarr;</a>' +
      "</div></div>";
  }

  // --- Public API ---

  window.StreamWidgets = {
    ProblemListWidget: ProblemListWidget,
    EncounterNoteWidget: EncounterNoteWidget,
    TaskListWidget: TaskListWidget,
    WaveformWidget: WaveformWidget,
    ProblemSummaryCard: ProblemSummaryCard,
  };
})();
